config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  root 'home#index'
  get 'home/index'
  get 'ranking/index'
  resources :progresses
  get 'update_progress/:id' => 'progresses#mark_complete', as: 'update_progress'
  get 'update_in_progress/:id' => 'progresses#mark_in_progress', as: 'update_in_progress'

  # API
  post '/add_weapon' => 'api#add_all_weapons'
  post '/submit_purchases' => 'api#submit_purchases'
  post '/open_game_session' => 'api#open_game_session'
  post '/close_game_session' => 'api#close_game_session'
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: %i[ show edit update destroy ]

  # GET /progresses or /progresses.json
  def index
    @maps = Progress.all.where(category: 'maps').order(:description)
    @models = Progress.all.where(category: 'models').order(:description)
    @audio = Progress.all.where(category: 'audio').order(:description)
    @cutscenes = Progress.all.where(category: 'cutscenes').order(:description)
    @enemies = Progress.all.where(category: 'enemies').order(:description)
    @features = Progress.all.where(category: 'features').order(:description)
    @heroes = Progress.all.where(category: 'heroes').order(:description)
    @ui = Progress.all.where(category: 'ui').order(:description)
    @bugs = Progress.all.where(category: 'bugs').order(:description)

    @corey_todo = Progress.all.where(assigned: 'Corey').order(:description)
    @syd_todo = Progress.all.where(assigned: 'Syd').order(:description)

    
    # Percent Variables
    total_complete_days = 0.0
    total_days = 0.0

    maps_complete_days = 0.0
    models_complete_days = 0.0
    audio_complete_days = 0.0
    cutscenes_complete_days = 0.0
    enemies_complete_days = 0.0
    features_complete_days = 0.0
    heroes_complete_days = 0.0
    ui_complete_days = 0.0

    maps_total_days = 0.0
    models_total_days = 0.0
    audio_total_days = 0.0
    cutscenes_total_days = 0.0
    enemies_total_days = 0.0
    features_total_days = 0.0
    heroes_total_days = 0.0
    ui_total_days = 0.0
    
    # Get Info From Records
    @maps.each do |m|
      total_days += m.expected_days
      maps_total_days += m.expected_days
      maps_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @models.each do |m|
      total_days += m.expected_days
      models_total_days += m.expected_days
      models_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @audio.each do |m|
      total_days += m.expected_days
      audio_total_days += m.expected_days
      audio_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @cutscenes.each do |m|
      total_days += m.expected_days
      cutscenes_total_days += m.expected_days
      cutscenes_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @enemies.each do |m|
      total_days += m.expected_days
      enemies_total_days += m.expected_days
      enemies_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @features.each do |m|
      total_days += m.expected_days
      features_total_days += m.expected_days
      features_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @heroes.each do |m|
      total_days += m.expected_days
      heroes_total_days += m.expected_days
      heroes_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    @ui.each do |m|
      total_days += m.expected_days
      ui_total_days += m.expected_days
      ui_complete_days += m.expected_days if(m.complete)
      total_complete_days += m.expected_days if(m.complete)
    end

    # Calculate Percent
    maps_percent = (maps_complete_days / maps_total_days * 100).ceil
    models_percent = (models_complete_days / models_total_days * 100).ceil
    audio_percent = (audio_complete_days / audio_total_days * 100).ceil
    cutscenes_percent = (cutscenes_complete_days / cutscenes_total_days * 100).ceil
    enemies_percent = (enemies_complete_days / enemies_total_days * 100).ceil
    features_percent = (features_complete_days / features_total_days * 100).ceil
    heroes_percent = (heroes_complete_days / heroes_total_days * 100).ceil
    ui_percent = (ui_complete_days / ui_total_days * 100).ceil
    total_percent = (total_complete_days / total_days * 100).ceil
    
    # Formatted
    @maps_progress = "#{maps_percent}% (#{(maps_total_days - maps_complete_days).ceil} Days Remaining)"
    @models_progress = "#{models_percent}% (#{(models_total_days - models_complete_days).ceil} Days Remaining)"
    @audio_progress = "#{audio_percent}% (#{(audio_total_days - audio_complete_days).ceil} Days Remaining)"
    @cutscenes_progress = "#{cutscenes_percent}% (#{(cutscenes_total_days - cutscenes_complete_days).ceil} Days Remaining)"
    @enemies_progress = "#{enemies_percent}% (#{(enemies_total_days - enemies_complete_days).ceil} Days Remaining)"
    @features_progress = "#{features_percent}% (#{(features_total_days - features_complete_days).ceil} Days Remaining)"
    @heroes_progress = "#{heroes_percent}% (#{(heroes_total_days - heroes_complete_days).ceil} Days Remaining)"
    @ui_progress = "#{ui_percent}% (#{(ui_total_days - ui_complete_days).ceil} Days Remaining)"
    @total_progress = "#{total_percent}% (#{(total_days - total_complete_days).ceil} Days Remaining)"
  end

  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses or /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to progresses_url }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1 or /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to progresses_path }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1 or /progresses/1.json
  def destroy
    @progress.destroy

    respond_to do |format|
      format.html { redirect_to progresses_path }
      format.json { head :no_content }
    end
  end

  def mark_complete
    process = Progress.find(params[:id])
    process.complete = !process.complete
    process.assigned = 'Unassigned'
    process.in_progress = false
    process.save
    redirect_to progresses_path
  end

  def mark_in_progress
    process = Progress.find(params[:id])
    process.in_progress = !process.in_progress
    process.complete = false
    process.save
    redirect_to progresses_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def progress_params
      params.require(:progress).permit(:category, :description, :expected_days, :complete, :notes, :assigned)
    end
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/_form.html.erb
<%= form_with(model: progress) do |form| %>
  <% if progress.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
        <% progress.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, size: '100%' %>
  </div> <!-- Description -->

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, [['Maps','maps'], ['Models','models'], ['Audio','audio'],
                                ['Cutscenes','cutscenes'], ['Enemies','enemies'], ['Features','features'],
                                ['Heroes','heroes'], ['UI','ui'], ['Bugs', 'bugs']] %>
  </div> <!-- Category -->

  <div>
    <%= form.label :expected_days, style: "display: block" %>
    <%= form.number_field :expected_days, max: 99, value: 1 %>
  </div> <!-- Expected Days -->

  <div>
    <%= form.label :assigned, style: "display: block" %>
    <%= form.select :assigned, [['Unassigned','Unassigned'], ['Corey','Corey'], ['Syd','Syd']] %>
  </div> <!-- Category -->

  <br/>

  <div>
    <h5><%= form.label :notes, style: "display: block" %></h5>
    <%= form.text_area :notes, size: '100x10' %>
  </div> <!-- Notes -->

  <br/><br/>

  <div>
    <%= form.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/progresses/_progress.html.erb
<div id="<%= dom_id progress %>">
  <p>
    <strong>Category:</strong>
    <%= progress.category %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= progress.description %>
  </p>

  <p>
    <strong>Expected days:</strong>
    <%= progress.expected_days %>
  </p>

  <p>
    <strong>Complete:</strong>
    <%= progress.complete %>
  </p>

</div>

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render "form", progress: @progress %>

<br/>

<div>
  <%= button_to "Delete Task", @progress, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/progresses/new.html.erb
<h1>New Task</h1>

<%= render "form", progress: @progress %>

<br>

<div>
  <%= button_to "Cancel", progresses_path, method: :get, class: 'btn btn-secondary' %>
</div>

app/views/progresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @progress %>

<div>
  <%= link_to "Edit this progress", edit_progress_path(@progress) %> |
  <%= link_to "Back to progresses", progresses_path %>

  <%= button_to "Destroy this progress", @progress, method: :delete %>
</div>